# Generated by Django 5.1.7 on 2025-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline of the news item.', max_length=200)),
                ('summary', models.TextField(help_text='A short summary (around 30 words) for quick reading.')),
                ('source_link', models.URLField(help_text='URL linking to the original article.')),
                ('date_published', models.DateTimeField(auto_now_add=True, help_text='Date and time when this news item was created.')),
            ],
        ),
    ]
