# Generated by Django 5.1.7 on 2025-03-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the news item.', null=True, upload_to='news_images/'),
        ),
    ]
