# Generated by Django 5.1.7 on 2025-03-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newsitem_image_newsitem_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='category',
            field=models.CharField(blank=True, help_text="Category of the news item (e.g., 'alerts', 'local', etc.)", max_length=100, null=True),
        ),
    ]
